# Generated by Django 5.2.16 on 2026-07-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('artifact_path', models.CharField(max_length=500)),
                ('metrics', models.JSONField(default=dict)),
                ('n_training_docs', models.PositiveIntegerField(default=0)),
                ('is_champion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='beat', max_length=40)),
                ('outcome', models.CharField(choices=[('running', 'Running'), ('promoted', 'Promoted'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('n_train_docs', models.PositiveIntegerField(default=0)),
                ('n_holdout_docs', models.PositiveIntegerField(default=0)),
                ('champion_f1', models.FloatField(blank=True, null=True)),
                ('challenger_f1', models.FloatField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
