# Generated by Django 5.2.16 on 2026-07-12 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('source', models.CharField(default='upload', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('doc_json', models.JSONField(blank=True, null=True)),
                ('is_holdout', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(default=list)),
                ('token_tags', models.JSONField(default=list)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('min_confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.modelversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.invoicedocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('predicted_value', models.TextField(blank=True, default='')),
                ('corrected_value', models.TextField()),
                ('predicted_confidence', models.FloatField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('accepted_as_is', models.BooleanField(default=False)),
                ('review_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='documents.extraction')),
            ],
        ),
    ]
